## 5-2.넘파이로 배열배우기

In [2]:
import numpy as np

a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [3]:
a.shape

(2, 2)

In [4]:
#배열 슬라이싱

d = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [5]:
d[1][2]

5

In [6]:
d[1,2]

5

In [7]:
d[1:, 3:] #1행 다음 3열의 수만 출력

array([[6, 7],
       [9, 9]])

In [8]:
d.dtype

dtype('int32')

In [9]:
d.astype(float)

array([[1., 2., 3., 4., 5.],
       [2., 4., 5., 6., 7.],
       [5., 7., 8., 9., 9.]])

In [10]:
#배열의 사칙연산 (리스트와 비교)

a = [1,2,3]
b = [0,1,2]

a+b

[1, 2, 3, 0, 1, 2]

In [11]:
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [12]:
a*b # 리스트는 연산이 안된다

TypeError: can't multiply sequence by non-int of type 'list'

In [14]:
#배열의 연산은 가능하다

x = np.arange(1,5)
y = np.arange(0,4)

print(x)
print(y)
print(x+y)

[1 2 3 4]
[0 1 2 3]
[1 3 5 7]


In [15]:
x-y

array([1, 1, 1, 1])

In [16]:
x*y

array([ 0,  2,  6, 12])

In [17]:
x/y

<ipython-input-17-a2dd4ac70d63>:1: RuntimeWarning: divide by zero encountered in true_divide
  x/y


array([       inf, 2.        , 1.5       , 1.33333333])

In [18]:
#list a,b  array x,y

a[:2] = 0


TypeError: can only assign an iterable

In [24]:
print(x)
x[:2]=1
print(x)

[0 0 3 4]
[1 1 3 4]
