In [19]:
import os, usecsv
import numpy as np
import csv, re
os.chdir(r'C:\Users\sunny\Desktop\python\do-it-python-master\05')
'''
설문조사 항목에 1점부터 5점까지 줌. 그러나 6점도 보임.
'''
data = usecsv.opencsv('quest.csv')
data

[['1', '2', '1', '2', '2'],
 ['1', '3', '2', '3', '2'],
 ['1', '4', '3', '3', '3'],
 ['2', '5', '4', '4', '4'],
 ['2', '5', '6', '2', '5'],
 ['3', '6', '4', '2', '5'],
 ['3', '5', '4', '1', '6'],
 ['3', '5', '5', '1', '3']]

In [20]:
#ghrtl tntwk tkdldp dlTdmf ','전처리 함수 연습
def switch(listname):
    for i in listname:
        for j in i:
            try:
                i[i.index(j)] = float(re.sub(',','',j))
            except:
                pass
    return listname
                    

In [22]:
switch(data)

[[1.0, 2.0, 1.0, 2.0, 2.0],
 [1.0, 3.0, 2.0, 3.0, 2.0],
 [1.0, 4.0, 3.0, 3.0, 3.0],
 [2.0, 5.0, 4.0, 4.0, 4.0],
 [2.0, 5.0, 6.0, 2.0, 5.0],
 [3.0, 6.0, 4.0, 2.0, 5.0],
 [3.0, 5.0, 4.0, 1.0, 6.0],
 [3.0, 5.0, 5.0, 1.0, 3.0]]

In [23]:
quest = np.array(data) #usecsv.switch
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 6., 2., 5.],
       [3., 6., 4., 2., 5.],
       [3., 5., 4., 1., 6.],
       [3., 5., 5., 1., 3.]])

In [24]:
quest >5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [25]:
quest[quest >5]

array([6., 6., 6.])

In [26]:
quest[quest >5] = 5

In [27]:
quest >5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [28]:
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])

In [29]:
usecsv.writecsv('resultcsv.csv', list(quest))